### ISSUE TITLE
can you support msvc and i686 targets

### ISSUE THREAD

**Issue by okeyzero** [Bromeon/js-sandbox#28]
i686-pc-windows-msvc

**Comment by okeyzero** [comment]
> Hey, thanks for the interest. Would you be willing to add support in a pull request?

I want to, too, but I'm not very good at it.

**Comment by Bromeon** [comment]
I mean, it needs some research. If it's important to you, you can consider spending some time on it, and I can help review.

But I maintain multiple open-source projects next to a full-time job, and don't have enough time to treat this issue tracker as a wishlist to fulfill, sorry :slightly_smiling_face:

Since I haven't heard more, I'll close this, but feel free to open a PR in case there's more interest.
